import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#f0f2f3',
    fontSize: 41 / 2,
    fontWeight: '700',
    marginRight: 36,
  },
  headerSpacer: {
    width: 36,
  },
  searchWrap: {
    marginTop: 10,
    marginHorizontal: 16,
    backgroundColor: '#1d222e',
    borderRadius: 24,
    height: 54,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchText: {
    color: '#6e7b84',
    fontSize: 42 / 2,
    fontWeight: '500',
  },
  content: {
    flex: 1,
  },
  contentInner: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 110,
  },
  happeningTitle: {
    color: '#f4f6f7',
    fontSize: 56 / 2,
    fontWeight: '800',
    marginBottom: 2,
  },
  happeningSubtitle: {
    color: '#6f7b85',
    fontSize: 42 / 2,
    marginBottom: 18,
  },
  spaceCard: {
    backgroundColor: '#6f49e2',
    borderRadius: 18,
    paddingTop: 14,
    marginBottom: 16,
    overflow: 'hidden',
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  liveLabel: {
    color: '#f4f4f4',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  cardTitle: {
    color: '#ffffff',
    fontSize: 53 / 2,
    lineHeight: 34,
    fontWeight: '800',
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  cardTags: {
    color: '#efeafd',
    fontSize: 38 / 2,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  listenersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  listenersStack: {
    flexDirection: 'row',
    marginRight: 8,
  },
  listenerAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#6f49e2',
  },
  listenersText: {
    color: '#efeaff',
    fontSize: 42 / 2,
  },
  hostPanel: {
    backgroundColor: 'rgba(47, 25, 120, 0.45)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.16)',
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  hostAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 8,
  },
  hostMeta: {
    flex: 1,
  },
  hostTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  hostName: {
    color: '#f4f6ff',
    fontSize: 19,
    fontWeight: '700',
  },
  roleBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  roleText: {
    color: '#f6f6ff',
    fontSize: 17 / 1.2,
    fontWeight: '600',
  },
  hostBio: {
    color: '#ebe7ff',
    fontSize: 18,
    lineHeight: 24,
  },
  fab: {
    position: 'absolute',
    right: 20,
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#5f6fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
